// Vercel Serverless Function — handles all /api/* requests.
//
// This imports the pre-built Express app bundle (artifacts/api-server/dist/app.mjs)
// which is produced by `pnpm run build:api` during Vercel's build step.
//
// Limitations vs the full server:
//   - Socket.io real-time rooms are not available (serverless can't hold connections)
//   - Everything else (movies, auth, search, music, proxy) works normally
//
// Required environment variables in Vercel:
//   DATABASE_URL  — PostgreSQL connection string (use Neon free tier)
//   JWT_SECRET    — any long random string

// @ts-ignore — generated by esbuild during build, not a source file
import app from "../artifacts/api-server/dist/vercel/app.vercel.mjs";

export default app;
